// The niche categories SOCIA understands. Shared by the onboarding wizard,
// the settings profile form, and the AI account-analysis route.
export const NICHES = [
  "Food & Restaurant",
  "Fitness & Health",
  "Beauty & Skincare",
  "Fashion & Style",
  "Travel",
  "Tech & Gadgets",
  "Education & How-to",
  "Gaming",
  "Business & Finance",
  "Lifestyle & Vlogs",
  "Home & Decor",
  "Real Estate",
  "Music & Entertainment",
  "Parenting & Family",
  "Art & Design",
  "Pets & Animals",
  "Automotive",
  "Other",
];
